#! /usr/bin/env bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

token=${1#myapp://none}
gnome-terminal -- /bin/bash -c "$SCRIPTPATH/../src/client.js --offer-token $token; sleep 5"
